/**
 * English dictionary — and, by inference, the shape every other locale must satisfy.
 *
 * `Dict` is derived from this object with `typeof`, so a missing or misspelled key in
 * another locale is a compile error rather than a string that silently falls back to
 * English at runtime.
 *
 * Entries are functions wherever grammar depends on the values. Templating with
 * placeholders alone does not survive translation: French needs agreement, elision
 * ("de" vs "d'"), and different plural rules, and those decisions belong in the locale
 * file rather than at the call site.
 */
import type { ChcDomain, ErrorType, ItemTypeId } from '../types';

const en = {
  locale: {
    /** BCP 47 tag for the <html lang> attribute. */
    htmlLang: 'en',
    /** How this language names itself, for the switcher. */
    nativeName: 'English',
    /** Intl locale used for number and date formatting. */
    intl: 'en-GB',
  },

  nav: {
    brand: 'Flex Your Neurons',
    home: 'Home',
    practice: 'Practice',
    test: 'Full test',
    progress: 'Progress',
    about: 'About',
    mainNav: 'Main',
    skipToContent: 'Skip to content',
    languageLabel: 'Language',
    switchTo: (name: string) => `Switch to ${name}`,
  },

  footer: {
    generated:
      'Every item here is generated by an algorithm and checked to have exactly one defensible answer. No item from any published test is reproduced.',
    noScore: 'This is practice, not assessment. It reports no IQ score, because it has no norms to report one against.',
    whyItMatters: 'Why that matters',
    terms: 'Terms of use',
  },

  domains: {
    Gf: 'Fluid reasoning',
    Gc: 'Comprehension-knowledge',
    Gv: 'Visual processing',
    Gwm: 'Working memory',
    Gs: 'Processing speed',
  } as Record<ChcDomain | 'Gc', string>,

  quiz: {
    preparing: 'Preparing items…',
    level: (n: number) => `Level ${n}`,
    progress: (current: number, total: number) => `${current} of ${total}`,
    answerOptions: 'Answer options',
    optionLabel: (n: number, description: string) => `Option ${n}: ${description}`,
    tip: (max: number) => ({ before: 'Tip: press ', after: ` to answer.`, first: '1', last: String(max) }),
    correct: 'Correct',
    notQuite: 'Not quite',
    next: 'Next',
    seeResults: 'See results',
    youTyped: (value: string) => `You typed ${value}.`,
    nothing: '(nothing)',
    yourAnswer: 'Your answer',
    typeSequence: 'Type the sequence',
    watching: 'Watch…',
    submit: 'Submit',
    nowTypeItBack: 'Now type it back.',
    /**
     * The span task is the one item that plays itself, so it is the one item that can be
     * missed by not looking. It used to begin 400ms after the page appeared, which meant a
     * reader who was still settling in simply lost the sequence with no way to replay it.
     */
    spanReady: (length: number) =>
      `${length} characters, one at a time. Each disappears as it goes — then you type them back.`,
    spanStart: 'Start the sequence',
    nBackReady: (length: number, n: number) =>
      `${length} letters, one at a time. Count the ones that repeat the letter ${n === 1 ? 'immediately before' : `${n} places earlier`}.`,
    nBackDone: 'How many were there?',
    /** Labels for the balance scales. View strings, so they live here, not in `gen`. */
    weights: {
      premisesLabel: 'These scales balance',
      targetLabel: 'Balance this one',
      premiseLabel: (n: number) => `Balanced scale ${n}`,
    },
    /** Labels for the digit-symbol key. View strings, so they live here, not in `gen`. */
    coding: {
      keyLabel: 'Key',
      probeLabel: 'Find this digit',
      pairLabel: (digit: string, description: string) => `${digit} is paired with ${description}`,
    },
    missingCell: 'missing cell',
    missingFigure: 'missing figure',
    patternMatrix: 'Pattern matrix',
    cellLabel: (n: number, description: string) => `Cell ${n}: ${description}`,
    figureLabels: {
      first: 'First figure',
      second: 'Second figure',
      third: 'Third figure',
      target: 'Target shape',
      targets: 'Targets',
      searchGroup: 'Search group',
      sheetBefore: 'The sheet before folding',
      sheetFolded: 'The folded sheet, with punches',
      sheet: 'sheet',
      punched: 'punched',
      foldStep: (fold: string) => `fold ${fold}`,
      step: (n: number) => `Step ${n}`,
      layers: (n: number) => `${n} layers`,
      /** Accessible description of one frame of the folding diagram. */
      foldFrameLabel: (n: number, description: string) => `Step ${n}: ${description}`,
      punchedFrameLabel: (layers: number) =>
        `The folded sheet, ${layers} layers thick, with the punches marked`,
    },
    describeFigure: (count: number, shape: string, size: number, shading: string) =>
      `${count} ${shape}${count === 1 ? '' : 's'}, size ${size}, ${shading}`,
    describeGrid: (cells: number) => `a shape of ${cells} cells`,
    emptyCell: 'an empty cell',
    unfilled: 'unfilled',
    shadingLevel: (n: number) => `shading level ${n}`,
    shapeNames: {
      circle: 'circle',
      square: 'square',
      triangle: 'triangle',
      diamond: 'diamond',
      pentagon: 'pentagon',
      hexagon: 'hexagon',
      star: 'star',
      cross: 'cross',
    },
  },

  /**
   * The keyboard shortcuts sheet.
   *
   * The shortcuts themselves have worked from the beginning; what was missing was any way to
   * find out about them. A `?` sheet is the convention readers already know from every other
   * keyboard-driven tool, so it needs no explaining of its own.
   */
  shortcuts: {
    open: 'Keyboard shortcuts',
    /** Hint shown next to the quiz, which is the only place the shortcuts apply. */
    hint: 'Press ? for keyboard shortcuts',
    heading: 'Keyboard shortcuts',
    lede: 'A whole drill can be answered without touching the mouse.',
    close: 'Close',
    keys: {
      numbers: 'Choose an answer',
      enter: 'Start a sequence, or continue to the next item',
      tab: 'Move between the options',
      question: 'Show or hide this list',
      escape: 'Close this list',
    },
    /** Rendered between the first and last option key, e.g. "1 – 8". */
    range: (first: string, last: string) => ({ first, last }),
  },

  /**
   * Copy for the build-time social cards.
   *
   * A preview image travels to places where none of the site's surrounding text does, so
   * the "no score" position has to be on the image itself — short enough to read at
   * thumbnail size in a chat window.
   */
  og: {
    disclaimer: 'Practice, not assessment. No IQ score, ever.',
  },

  /**
   * The seed, promoted from a URL parameter to something a reader can see and pass on.
   *
   * Replaying an exact item in either language is this site's most distinctive capability
   * and it used to be invisible — discoverable only by noticing `?seed=` in the address
   * bar. These strings are what make it an offer rather than an implementation detail.
   */
  seed: {
    label: 'Seed',
    /** Accessible name for the copy control; the visible glyph is decorative. */
    copy: 'Copy the link that replays this run',
    copyShort: 'Copy link',
    copied: 'Link copied',
    copyFailed: 'Could not copy — select the seed and copy it by hand.',
    explain:
      'This eight-character seed is the whole run. Anyone opening the copied link gets exactly these items, in whichever language they read — nothing is stored on a server, because the seed regenerates the items on their own machine.',
  },

  /**
   * The error-type taxonomy, in words.
   *
   * Every distractor already carries a machine-readable diagnosis (`Item.errorTypes`,
   * from Wang & Su — docs/IQ-TESTS.md §5.1). These strings are what turn that from a
   * verdict into a lesson: not "wrong", but *which* misreading this was.
   *
   * The wording is deliberately format-neutral. A matrix, an analogy and a folded sheet
   * can all be misread "one step too far", and the diagnosis is more useful stated as the
   * general habit than as a fact about this one item — the item-specific part is already
   * in `explanation.rules`.
   */
  diagnosis: {
    heading: 'What went wrong',
    /** Short label for the monospace chip. Lower case: it is a tag, not a sentence. */
    tags: {
      correct: 'correct',
      'wrong-rule': 'wrong rule',
      'wrong-axis': 'wrong axis',
      'off-by-one': 'off by one',
      copy: 'copied cell',
      'wrong-attribute': 'wrong attribute',
      mirror: 'mirrored',
      plausible: 'near miss',
    } as Record<ErrorType, string>,
    bodies: {
      correct: 'You applied every rule the item was built from.',
      'wrong-rule':
        'Right feature, wrong rule. You spotted which attribute changes, then applied a different transformation to it than the one the item is built on.',
      'wrong-axis':
        'Right rule, wrong direction. You read down the column instead of across the row. The rules here run along the rows; the columns only appear to be patterned because the rows are.',
      'off-by-one':
        'Right rule, one step too far. The transformation is applied once more — or once less — than the pattern calls for. Count the steps rather than eyeballing the end point.',
      copy: 'That option simply repeats a figure already on screen. Something already visible can never be the missing part of the pattern.',
      'wrong-attribute':
        'Right rule, wrong feature. The transformation you applied is a real one here, but it governs a different attribute from the one you moved.',
      mirror:
        'That is a reflection, not a rotation. Pick one asymmetric feature and follow it: turning preserves its position relative to the rest, flipping reverses it.',
      plausible:
        'A near miss with no single diagnosis — it breaks the pattern in more than one way at once, so there is no one rule to correct.',
    } as Record<ErrorType, string>,
    /** Chip on a distractor once the answer is revealed. */
    optionTag: (tag: string) => `wrong: ${tag}`,
    /** Appended to a distractor's accessible name once revealed. */
    optionAria: (tag: string) => `Incorrect — ${tag}.`,
    answerLabel: 'The answer',
  },

  results: {
    heading: 'Session complete',
    /** The error-type breakdown for the session just finished. */
    mistakesHeading: 'How you went wrong',
    mistakesLede:
      'Every wrong answer here is a specific misreading, and the same misreading tends to repeat. This is the one thing worth taking away from a session.',
    mistakesNone: 'Nothing to break down — you got every item right.',
    /** The headline finding: the single commonest way this session went wrong. */
    commonestMistake: (tag: string, n: number, total: number) =>
      `${n} of your ${total} wrong answer${total === 1 ? '' : 's'} ${n === 1 ? 'was' : 'were'} the same mistake: ${tag}.`,
    mistakesSpread:
      'Your wrong answers were spread across several different mistakes, with no single habit standing out.',
    correct: 'Correct',
    accuracy: 'Accuracy',
    medianTime: 'Median time',
    seed: 'Seed',
    byItemType: 'By item type',
    colType: 'Type',
    colCorrect: 'Correct',
    colAccuracy: 'Accuracy',
    disclaimerBefore: 'This is your score on these items, not an IQ. There are no norms behind it — see ',
    disclaimerLink: 'what this does and does not measure',
    disclaimerAfter: '.',
    goAgain: 'Go again',
    seeProgress: 'See progress',
  },

  dashboard: {
    loading: 'Loading…',
    overall: 'Overall',
    itemsAnswered: 'Items answered',
    accuracy: 'Accuracy',
    medianTime: 'Median time',
    sessions: 'Sessions',
    dayStreak: 'Day streak',
    byDomain: 'By cognitive domain',
    domainChartLabel: 'Accuracy by cognitive domain',
    domainLede:
      'Your accuracy on the four Cattell–Horn–Carroll broad abilities these formats load on. A profile, not a score: there is no norm behind any of these bars, so they compare you with yourself and with nobody else.',
    /** Marks a bar with too few attempts to mean anything yet. */
    provisional: (attempts: number) =>
      `${attempts} item${attempts === 1 ? '' : 's'} — too few to read anything into`,
    provisionalKey: 'Faded bars have fewer than ten items behind them.',

    /** The empty state, which for a new reader is the whole page. */
    emptyHeading: 'Nothing here yet — and that is the point',
    emptyBody:
      'This page is the only one that holds your own data, so it starts empty. Finish one drill and it fills with your accuracy, your speed, the formats you find hard, and the specific mistakes you keep making.',
    emptyCtaPractice: 'Practise one format',
    emptyCtaTest: 'Take the full test',
    emptyPrivacy:
      'Everything stays in this browser. There is no account and no server to send it to.',

    /** Accuracy against latency — the speed/accuracy trade-off. */
    speed: {
      heading: 'Accuracy against speed',
      lede: 'One dot per format, placed by how accurate you are and how long you take. Formats towards the top-left are the ones you have internalised; towards the bottom-right are the ones you are still working out.',
      label: 'Accuracy against median response time, one point per item format',
      axisX: 'Median time per correct answer',
      axisY: 'Accuracy',
      /** Tooltip and accessible description for one point. */
      point: (name: string, accuracy: string, time: string, attempts: number) =>
        `${name}: ${accuracy} accurate over ${attempts} item${attempts === 1 ? '' : 's'}, ${time} median`,
      needMore:
        'Answer at least five items in two or more formats and the trade-off between speed and accuracy will show up here.',
      fastest: 'quickest',
      mostAccurate: 'most accurate',
    },

    /** The error-type breakdown, fed by the diagnosis on every wrong answer. */
    mistakes: {
      heading: 'The mistakes you keep making',
      lede: 'Every wrong answer is a specific misreading, named at the time you made it. Across your whole history one or two usually dominate — and those are worth knowing, because they are habits rather than gaps.',
      label: 'How often each kind of mistake occurs',
      empty:
        'No diagnosed mistakes yet. Each wrong answer in a drill is labelled with the misreading behind it, and they accumulate here.',
      /** Tooltip for one bar. */
      bar: (tag: string, count: number, share: string) =>
        `${tag}: ${count} time${count === 1 ? '' : 's'} (${share} of your diagnosed mistakes)`,
      colShare: 'Share',
    },

    /** Small multiples: one trend per format. */
    wall: {
      heading: 'Every format, over time',
      lede: 'One trace per format, oldest attempts on the left. Small charts side by side rather than thirteen lines on one axis — thirteen colours on one plot would be unreadable, and these are meant to be scanned for shape, not read for values.',
      never: 'not attempted yet',
    },
    byItemType: 'By item type',
    colType: 'Type',
    colDomain: 'Domain',
    colAnswered: 'Answered',
    colAccuracy: 'Accuracy',
    colMedianTime: 'Median time',
    colBestRun: 'Best run',
    colPeakLevel: 'Peak level',
    settings: 'Settings',
    settingFeedback: 'Explain each answer as I go',
    settingFeedbackHint: 'Turn off for an uninterrupted, test-like run.',
    settingAdaptive: 'Adapt difficulty to my performance',
    settingAdaptiveHint: 'Three right in a row moves up a level; two wrong moves down.',
    settingMotion: 'Slow down the digit-span playback',
    settingMotionHint: 'Digit span elements are shown for longer.',
    settingLength: 'Items per practice drill',
    yourData: 'Your data',
    storageNote: (sessions: number) =>
      `Everything is stored in this browser's localStorage. Nothing is sent anywhere — there is no server to send it to. ${sessions} session${sessions === 1 ? '' : 's'} saved.`,
    exportJson: 'Export JSON',
    importJson: 'Import JSON',
    reset: 'Reset history',
    resetConfirm: 'Yes, delete everything',
    resetCancel: 'Cancel',
    historyCleared: 'History cleared.',
    charts: {
      heading: 'Progress over time',
      lede: 'Your own numbers, session by session. A rising line means you are getting better at these formats — not that anything underlying has changed.',
      accuracyTitle: 'Accuracy per session',
      accuracyLabel: 'Accuracy per session, oldest on the left',
      speedTitle: 'Median time per correct answer',
      speedLabel: 'Median response time per session, oldest on the left',
      activityTitle: 'Activity',
      activityLabel: 'Items answered per day over the last eight weeks',
      rollingAverage: 'Rolling average over 3 sessions',
      needMore: 'Finish a couple more sessions and a trend will appear here.',
      noActivity: 'No activity in the last eight weeks.',
      session: (n: number) => `Session ${n}`,
      describeDay: (items: number, correct: number) =>
        `${items} item${items === 1 ? '' : 's'}, ${correct} correct`,
      today: 'today',
      weeksAgo: (n: number) => `${n} weeks ago`,
      colTrend: 'Trend',
      trendLabel: (type: string) => `Accuracy trend for ${type}`,
      improvedBy: (points: number) =>
        `Your accuracy is up ${points} percentage point${points === 1 ? '' : 's'} compared with the first half of your history.`,
      declinedBy: (points: number) =>
        `Your accuracy is down ${points} percentage point${points === 1 ? '' : 's'} compared with the first half of your history. Difficulty rises as you improve, so this is expected as much as it is discouraging.`,
      steady: 'Your accuracy is holding steady compared with the first half of your history.',
    },
  },

  storeMessages: {
    notJson: 'That file is not valid JSON.',
    missingSchema: 'Missing schema version — this is not an export from this app.',
    schemaMismatch: (theirs: number, ours: number) =>
      `That export uses schema v${theirs}; this version reads v${ours}.`,
    noSessions: 'No usable sessions found in that file.',
    imported: (n: number) => `Imported ${n} session${n === 1 ? '' : 's'}.`,
    importedPartial: (added: number, already: number) =>
      `Imported ${added} new session${added === 1 ? '' : 's'}; ${already} were already here.`,
  },

  items: {
    matrix: {
      name: 'Matrix reasoning',
      blurb: 'Find the figure that completes the 3×3 pattern.',
      description:
        'A 3×3 grid of figures with the bottom-right cell missing. Attributes — shape, size, shading, count and arrangement — each follow a rule across the rows. Infer the rules and pick the figure that completes them. This is the canonical non-verbal test of fluid reasoning and the format most closely associated with g.',
      seenIn: "Raven's Progressive Matrices, WAIS Matrix Reasoning, Cattell CFIT, NNAT",
    },
    'series-number': {
      name: 'Number series',
      blurb: 'Work out the rule and continue the sequence.',
      description:
        'A sequence of integers built from a hidden rule — a constant gap, a growing gap, two interleaved sequences, repeating blocks, or a multiplier that itself changes. Difficulty follows the five ANSIG cognitive operators, which together account for about 77% of item-difficulty variance in the published item-generation literature.',
      seenIn: 'Cattell CFIT, Wonderlic, CogAT Quantitative, most aptitude batteries',
    },
    'series-letter': {
      name: 'Letter series',
      blurb: 'Continue the pattern through the alphabet.',
      description:
        'A sequence of letters that advances through the alphabet by a hidden rule: a fixed step, two alternating steps, or a step that grows. It is the same inductive-reasoning task as number series, using a familiar ordered set rather than arithmetic, so calculation skill interferes less with the reasoning being measured.',
      seenIn: 'CogAT, Wonderlic, 11-plus and civil-service aptitude batteries',
    },
    'odd-one-out': {
      name: 'Odd one out',
      blurb: 'Four figures share a property. One does not.',
      description:
        'All but one of the figures share a defining property — the same shape, the same shading, the same size, or the same number of elements — while varying freely in other respects. Find the one that breaks the rule. Every item is checked so that exactly one figure is defensibly odd, on exactly one dimension.',
      seenIn: 'Cattell CFIT Classification, CogAT Figure Classification, NNAT',
    },
    'analogy-figural': {
      name: 'Figural analogy',
      blurb: 'A is to B as C is to… which figure?',
      description:
        'Work out how the first figure was changed into the second — a change of size, shading, orientation or shape — then apply exactly the same change to the third figure. Analogical mapping is one of the purest measures of inductive reasoning, and it isolates rule transfer rather than rule discovery.',
      seenIn: "WAIS Matrix Reasoning (analogy items), CogAT Figure Analogies, Raven's",
    },
    syllogism: {
      name: 'Syllogisms',
      blurb: 'Decide what follows — and what only seems to.',
      description:
        'Two premises about three categories. Choose the conclusion that must be true, or say that none does. Invented category names are used deliberately: with real-world categories, believability substitutes for deduction. Validity is decided here by exhaustive model checking, so the key is proved rather than assumed.',
      seenIn: 'Critical-reasoning sections of the GMAT, LSAT, UCAT and Watson–Glaser',
    },
    rotation: {
      name: 'Mental rotation',
      blurb: 'Spot the same shape, turned — not flipped.',
      description:
        'One of the options is the target shape rotated; the rest are mirror images or near-misses. The distinction between a rotation and a reflection is the heart of the task, so every shape is verified to be chiral — a shape identical to its own mirror image would make the item unanswerable.',
      seenIn: 'Vandenberg & Kuse Mental Rotations Test, Shepard & Metzler (1971), DAT Spatial',
    },
    'paper-folding': {
      name: 'Paper folding',
      blurb: 'Fold, punch, unfold — where are the holes?',
      description:
        'A square sheet is folded once or twice, then holes are punched through every layer. Work out where the holes appear when the sheet is opened out again. This is spatial visualisation rather than rotation: you have to hold and transform a mental image through several steps.',
      seenIn: 'ETS Paper Folding Test (VZ-2), DAT Space Relations, many entrance exams',
    },
    span: {
      name: 'Digit span',
      blurb: 'Hold a sequence in mind — then say it back.',
      description:
        'A sequence appears one element at a time, then you type it back. Forward span measures simple storage; backward span requires you to hold the sequence and reverse it, which is why it loads on working memory rather than short-term storage alone. Sequences lengthen as difficulty rises.',
      seenIn: 'WAIS Digit Span, WISC Digit Span, Stanford–Binet Memory for Digits',
    },
    'symbol-search': {
      name: 'Symbol search',
      blurb: 'Is either symbol in the group? Answer fast.',
      description:
        'Two target symbols, then a group to scan. Say whether either target appears. Each item is easy on its own — the measure is how fast you can do many of them without slipping. Because accuracy stays near ceiling, this type is scored on median response time rather than on percentage correct.',
      seenIn: 'WAIS Symbol Search, WISC Symbol Search, WAIS Coding (same index)',
    },
    'figure-weights': {
      name: 'Figure weights',
      blurb: 'The scales balance. Which group balances the last one?',
      description:
        'A set of balance scales, each showing what balances what. Those premises give every shape a weight relative to the others; the last scale is missing one pan, and you pick the group that balances it. Because the shapes are values and the scales are equations, this is quantitative reasoning without any arithmetic notation — and it is decidable, so exactly one option can balance. The commonest mistake is matching the number of objects instead of their weight.',
      seenIn: 'WAIS-IV and WISC-V Figure Weights, Cattell CFIT (Conditions), quantitative-reasoning subtests generally',
    },
    'n-back': {
      name: 'N-back',
      blurb: 'Count the letters that repeat N places back.',
      description:
        'A stream of letters goes past one at a time. Count how many of them match the letter a fixed number of places earlier — one place back at first, up to three. Span asks you to hold a list still; this asks you to keep a moving window of the last few elements and rewrite it at every step, which is why it measures updating rather than storage. The stream is gone when you answer, and it does not replay.',
      seenIn: 'Cognitive-training and working-memory research (Jaeggi et al.), Cogmed, the dual n-back literature',
    },
    coding: {
      name: 'Digit–symbol coding',
      blurb: 'Read the key. Which symbol goes with the digit?',
      description:
        'A key pairs each digit with an abstract symbol. One digit is named; find its symbol in the key. Every option is a symbol that appears in the key, so the answer cannot be reached by elimination — the pairing has to be read. On the real battery this is a two-minute written sprint scored on how many substitutions you complete, so what is measured here is the speed of one substitution rather than sustained output.',
      seenIn: 'WAIS Coding, WISC Coding, Wechsler Digit Symbol, the Symbol Digit Modalities Test',
    },
  } as Record<ItemTypeId, { name: string; blurb: string; description: string; seenIn: string }>,

  gen: {
    /** Attribute names used by the matrix rule explanations. */
    matrixAttr: {
      number: 'The number of shapes',
      position: 'The arrangement of shapes',
      type: 'The shape',
      size: 'The size',
      color: 'The shading',
    },
    rules: {
      constant: (attr: string) => `${attr} stays the same across each row.`,
      progression: (attr: string, step: number) =>
        `${attr} ${step > 0 ? 'increases' : 'decreases'} by ${Math.abs(step)} at each step across the row.`,
      arithmeticAdd: (attr: string) => `${attr}: the third cell equals the first plus the second.`,
      arithmeticSub: (attr: string) => `${attr}: the third cell equals the first minus the second.`,
      distributeThree: (attr: string) =>
        `${attr}: the same three values appear in every row, in a different order.`,
      sameEverywhere: (attr: string) => `${attr} is the same in every cell.`,
    },

    matrix: {
      prompt: 'Which figure completes the pattern?',
      summary: (option: number) =>
        `Option ${option} is the only figure that satisfies every rule at once.`,
    },

    seriesNumber: {
      prompt: 'Which number continues the sequence?',
      summary: (value: number) => `The next term is ${value}.`,
      sequence: (terms: string) => `Sequence: ${terms}`,
      plusMinus: (d: number) => `Each term is the previous one ${d > 0 ? `plus ${d}` : `minus ${-d}`}.`,
      times: (m: number) => `Each term is the previous one multiplied by ${m}.`,
      timesPlus: (m: number, c: number) =>
        `Each term is the previous one times ${m}, ${c > 0 ? `plus ${c}` : `minus ${-c}`}.`,
      alternating: (a: number, b: number) =>
        `Two sequences alternate: the 1st, 3rd, 5th… terms go ${a > 0 ? `up by ${a}` : `down by ${-a}`}, while the 2nd, 4th, 6th… terms go ${b > 0 ? `up by ${b}` : `down by ${-b}`}.`,
      blocks: (size: number, step: number) =>
        `The sequence runs in blocks of ${size}; each block is ${step > 0 ? `${step} higher` : `${-step} lower`} than the one before.`,
      growingGap: (d0: number, d1: number, d2: number, dd: number) =>
        `The gaps between terms are ${d0}, ${d1}, ${d2}… — each gap ${dd > 0 ? `grows by ${dd}` : `shrinks by ${-dd}`}.`,
      fibonacci: 'Each term is the sum of the two terms before it.',
      growingFactor: (r0: number, r1: number, r2: number) =>
        `Each term is multiplied by a factor that grows each step: ×${r0}, ×${r1}, ×${r2}…`,
    },

    seriesLetter: {
      prompt: 'Which letter continues the sequence?',
      summary: (letter: string) => `The next letter is ${letter}.`,
      sequence: (letters: string) => `Sequence: ${letters}`,
      positions: (positions: string) => `Alphabet positions: ${positions}`,
      step: (step: number) =>
        `Each letter moves ${Math.abs(step)} position${Math.abs(step) === 1 ? '' : 's'} ${step > 0 ? 'forward' : 'backward'} in the alphabet.`,
      alternating: (a: number, b: number) =>
        `Two alphabet sequences alternate: the 1st, 3rd, 5th… letters move ${a > 0 ? `+${a}` : a}, the 2nd, 4th, 6th… move ${b > 0 ? `+${b}` : b}.`,
      growingStep: (d0: number, dd: number) =>
        `The gap between letters grows by ${dd} each step: +${d0}, +${d0 + dd}, +${d0 + 2 * dd}…`,
    },

    oddOneOut: {
      prompt: 'Which figure does not belong with the others?',
      dims: {
        type: 'shape',
        size: 'size',
        color: 'shading',
        count: 'number of elements',
      },
      summary: (option: number, dim: string) =>
        `Option ${option} is the odd one out: its ${dim} differs.`,
      shared: (dim: string) => `Every other figure shares the same ${dim}.`,
      noise: (dims: string[]) =>
        `${dims.join(' and ')} vary freely and are not the rule.`,
    },

    analogy: {
      prompt: 'The first figure changes into the second. Apply the same change to the third.',
      summary: (option: number, changes: string[]) =>
        `Option ${option}. Going from the first figure to the second, ${changes.join(', and ')}.`,
      rule: (change: string) => `Transformation: ${change}.`,
      sizeChange: (amount: number) =>
        `the shape gets ${amount > 0 ? 'larger' : 'smaller'} by ${Math.abs(amount)} step${Math.abs(amount) === 1 ? '' : 's'}`,
      colorChange: (amount: number) =>
        `the shading gets ${amount > 0 ? 'darker' : 'lighter'} by ${Math.abs(amount)} step${Math.abs(amount) === 1 ? '' : 's'}`,
      rotationChange: (degrees: number) => `the shape rotates ${degrees} degrees`,
      typeChange: (amount: number) =>
        `the shape changes to the one ${Math.abs(amount)} along in the set`,
    },

    syllogism: {
      prompt: 'Assume both statements are true. What must follow?',
      noConclusion: 'No valid conclusion follows from these premises.',
      propA: (s: string, p: string) => `All ${s} are ${p}.`,
      propE: (s: string, p: string) => `No ${s} are ${p}.`,
      propI: (s: string, p: string) => `Some ${s} are ${p}.`,
      propO: (s: string, p: string) => `Some ${s} are not ${p}.`,
      summaryValid: (option: number, conclusion: string) => `Option ${option}: ${conclusion}`,
      summaryNone: (option: number) => `Option ${option}: nothing follows with certainty.`,
      ruleValid: (conclusion: string, models: number) =>
        `"${conclusion}" holds in every one of the ${models} situations that satisfy both premises.`,
      ruleValidOthers:
        'Each of the other conclusions has at least one counterexample — a situation where the premises hold but the conclusion fails.',
      ruleNone: (models: number) =>
        `Of the ${models} situations that satisfy both premises, each candidate conclusion fails in at least one.`,
      ruleNoneHint: (minor: string, major: string) =>
        `Premises can be consistent with a relationship without guaranteeing it. Nothing about ${minor} and ${major} is forced here.`,
    },

    rotation: {
      prompt: 'Which shape is the one above, rotated?',
      summary: (option: number, degrees: number) =>
        `Option ${option} is the shape turned ${degrees}° clockwise.`,
      ruleMirrors:
        'The other options are mirror images — flipped, not turned. No amount of rotation in the plane will produce them.',
      ruleHint:
        'A quick check: pick an asymmetric feature (a lone protruding cell) and follow where it sits relative to the rest. Rotation preserves that relationship; reflection reverses it.',
    },

    paperFolding: {
      prompt: 'The sheet is folded, then punched. How does it look unfolded?',
      folds: {
        left: 'the left half is folded over onto the right',
        right: 'the right half is folded over onto the left',
        top: 'the top half is folded down onto the bottom',
        bottom: 'the bottom half is folded up onto the top',
      },
      /** Caption under a diagram frame: says which half moves and where it goes. */
      foldShort: {
        left: 'left folds right',
        right: 'right folds left',
        top: 'top folds down',
        bottom: 'bottom folds up',
      },
      summary: (option: number, punches: number, layers: number, holes: number) =>
        `Option ${option}: ${punches} punch${punches === 1 ? '' : 'es'} through ${layers} layers gives ${holes} holes.`,
      foldStep: (n: number, description: string) => `Fold ${n}: ${description}.`,
      ruleUnfold:
        'Each punch goes through every layer beneath it, so unfolding mirrors it back across each fold line in reverse order.',
    },

    span: {
      promptForward: 'Type the sequence back in the order it appeared.',
      promptBackward: 'Type the sequence back in reverse order.',
      summary: (shown: string, expected: string) =>
        `The sequence was ${shown}, so the answer is ${expected}.`,
      ruleBackward:
        'Backward span asks you to store the sequence and reverse it at the same time — that manipulation is what makes it a working-memory task rather than a storage one.',
      ruleForward: 'Forward span measures how much you can hold at once, with no manipulation.',
      ruleChunking: 'Grouping the elements into chunks of two or three as they arrive reliably extends span.',
    },

    symbolSearch: {
      prompt: 'Does either target symbol appear in the group?',
      yes: 'Yes',
      no: 'No',
      summaryPresent: 'Yes — one of the targets is in the group.',
      summaryAbsent: 'No — none of the targets is in the group.',
      ruleMatch: 'A symbol matches only if its shape, its shading and its orientation all match.',
      ruleSpeed:
        'This type is scored on speed: your median response time matters more than your accuracy, which should stay near ceiling.',
    },
    figureWeights: {
      prompt: 'Which group balances the last scale?',
      premisesLabel: 'These scales balance',
      targetLabel: 'Balance this one',
      summary: (group: string) => `${group} balances it.`,
      rulePremise: (heavier: string, ratio: number, lighter: string) =>
        `One ${heavier} weighs the same as ${ratio} ${lighter}s.`,
      ruleTarget: (group: string, weight: number) =>
        `The pan to match holds ${group}, which comes to ${weight} units of the lightest shape.`,
      ruleCount:
        'Weight is what balances, not the number of objects: a group with the right number of pieces and the wrong total will not balance.',
      quantity: (n: number, shape: string) => `${n} ${shape}${n === 1 ? '' : 's'}`,
      join: (parts: string[]) =>
        parts.length <= 1 ? (parts[0] ?? '') : `${parts.slice(0, -1).join(', ')} and ${parts.at(-1)}`,
    },
    nBack: {
      prompt: (n: number) =>
        n === 1
          ? 'How many letters were the same as the one immediately before?'
          : `How many letters were the same as the one ${n} places earlier?`,
      streamLabel: (n: number) => (n === 1 ? 'Watch for 1-back repeats' : `Watch for ${n}-back repeats`),
      summary: (count: number, n: number) =>
        `${count} letters matched the one ${n === 1 ? 'immediately before' : `${n} places earlier`}.`,
      ruleWindow: (n: number) =>
        n === 1
          ? 'A match is a letter identical to the one just before it.'
          : `A match is a letter identical to the one ${n} places earlier — the ${n - 1} letters in between do not matter.`,
      rulePairs: (pairs: string) => `The matching positions were ${pairs}.`,
      ruleUpdating:
        'Counting these means holding the last few letters and replacing the oldest at every step. That updating, rather than how much you can store, is what this format measures.',
    },
    coding: {
      prompt: (digit: string) => `Which symbol is paired with ${digit}?`,
      summary: (digit: string, column: number) =>
        `${digit} is in column ${column} of the key, and that column's symbol is the answer.`,
      ruleLookup: 'The key is the whole item: each digit is paired with exactly one symbol.',
      ruleColumn:
        'Every option appears somewhere in the key, so the answer cannot be found by elimination — and the commonest mistake is reading the column beside the right one.',
      ruleSpeed:
        'This type is scored on speed: your median response time matters more than your accuracy, which should stay near ceiling.',
    },
  },

  pages: {
    home: {
      title: 'Train on reasoning-test formats',
      description:
        'Practise the item formats used in IQ and aptitude tests — matrix reasoning, number series, syllogisms, mental rotation and more. Every item is generated fresh, verified to have one answer, and explained afterwards. Runs entirely in your browser.',
      lede: 'Thirteen item formats from the intelligence-testing literature, generated fresh every time and explained after every answer. No account, no server, no score you should put on a CV.',
      ctaTest: 'Take a full test',
      ctaPractice: 'Practise one format',
      whatHeading: 'What you can train',
      whatLede:
        'Grouped by the Cattell–Horn–Carroll broad abilities the formats load on. Fluid reasoning (Gf) is the closest single proxy for general ability, and also the most procedurally generatable — which is why abstract-reasoning items dominate every free test you have met.',
      seenIn: (tests: string) => `Seen in: ${tests}`,
      howHeading: 'How the items are made',
      how: [
        {
          title: 'Generated, never stored',
          body: 'An eight-character seed reproduces an item exactly. There is no item bank, so there is nothing to leak and nothing to memorise.',
        },
        {
          title: 'Proved to have one answer',
          body: 'A separate solver re-derives each item from scratch. If two different rules fit and disagree, the item is thrown away and regenerated.',
        },
        {
          title: "Distractors that can't be reverse-engineered",
          body: 'Options are balanced so the answer is never the most "typical" one — the flaw that made a well-known research dataset solvable without looking at the question.',
        },
        {
          title: 'Explained every time',
          body: 'Because the generator built the item from an explicit rule, it can always state that rule afterwards. Being told "wrong" teaches nothing.',
        },
      ],
      clearHeading: 'One thing to be clear about',
      clearBody:
        'This site will never show you an IQ number. A real IQ score is a comparison against a representative sample of people your age, tested under standardised conditions — and no website has that. Any site that gives you a number after ten questions is making it up.',
      clearBodyAfter: 'What you can honestly get here is practice, and an accurate picture of your own accuracy and speed over time. ',
      clearLink: 'The longer version, including why practice effects mean training helps your test score more than your reasoning',
    },

    practiceIndex: {
      title: 'Practice',
      description:
        'Pick a single reasoning-test item format and drill it, with difficulty that adapts to how you are doing and an explanation after every answer.',
      lede: 'Drill one format at a time. Difficulty adapts as you go — three right in a row moves you up, two wrong moves you back down — so you stay near the level where practice actually does something.',
    },

    practiceType: {
      aboutHeading: 'About this format',
      seenIn: (tests: string) => `Seen in: ${tests}`,
    },

    test: {
      title: 'Full test',
      description:
        'A mixed run across all thirteen reasoning-test formats, two items each, with no feedback until the end.',
      lede: 'Twenty-six items, two from each format, presented in a fixed rotation with no feedback until you finish. Closer to how a real battery feels than the practice drills are.',
      differsHeading: 'How this differs from a real battery',
      differs: [
        'A real battery is administered one-to-one by a trained examiner with fixed instructions, timing and stop rules. This is you, alone, in a browser tab.',
        'A real battery converts your raw score against an age-matched standardisation sample. There is no sample here, so there is no percentile and no IQ — only your own numbers.',
        'A real battery includes verbal comprehension, which cannot be procedurally generated with verifiable answers. Nothing here measures it.',
        'Twenty-six items is far too few for a stable estimate of anything. Published batteries use ten to fifteen subtests for a reason.',
      ],
    },

    progress: {
      title: 'Progress',
      description:
        'Your accuracy, speed and streaks per item format and per cognitive domain — stored only in this browser.',
      lede: 'Your own numbers, and nobody else’s. Accuracy tells you whether you have understood a format; median time tells you whether you have internalised it.',
    },

    about: {
      title: "What this measures, and what it doesn't",
      description:
        'How IQ tests are built, which item formats can be generated and verified by a program, and why this site deliberately reports no IQ score.',
      lede: 'The honest version. What an IQ test actually is, which parts of one a program can legitimately reproduce, and why the number you are probably looking for is not here.',

      procedureHeading: 'An IQ test is a procedure, not a set of questions',
      procedureP1:
        'This is the single most misunderstood thing about intelligence testing. A test is a standardised battery of subtests. Your raw score on each is converted to a scaled score by comparing it against a norming sample — thousands of people matched to your age, tested under controlled conditions — and those are combined into index scores and a composite, conventionally scaled to mean 100 and standard deviation 15.',
      procedureP2:
        'Three things make that number mean something, and every one of them is a property of the administration rather than of the questions:',
      procedureList: [
        'A representative standardisation sample to compare against.',
        'Fixed instructions, timing, order and stop rules.',
        'Published reliability and validity — major batteries report test–retest correlations of 0.85–0.95.',
      ],
      procedureP3:
        'A program can generate questions that behave like subtest items. It cannot generate norms. That single gap determines everything about how this site is built.',

      chcHeading: 'The map: CHC theory',
      chcP1:
        'Nearly every modern battery is organised around the Cattell–Horn–Carroll model: general ability g at the top, about ten broad abilities beneath it, and seventy-odd narrow abilities below those. The four broad abilities this site trains:',
      chcColCode: 'Code',
      chcColAbility: 'Ability',
      chcColFormats: 'Formats here',
      chcNote:
        'Missing from that list: Gc, comprehension-knowledge — vocabulary, verbal analogies, general information. That absence is deliberate and explained below.',

      familiesHeading: 'The major test families',
      families: [
        {
          name: 'Wechsler scales (WAIS-IV, WISC-V, WPPSI-IV)',
          body: 'The most widely used clinical batteries. Ten core subtests produce four index scores — Verbal Comprehension, Perceptual Reasoning, Working Memory, Processing Speed — and a Full Scale IQ. Administered one-to-one by a qualified examiner.',
        },
        {
          name: 'Stanford–Binet 5',
          body: 'Five factors (fluid reasoning, knowledge, quantitative reasoning, visual-spatial processing, working memory), each measured in both a verbal and a non-verbal form — a 5×2 design, with routing subtests that set where you start.',
        },
        {
          name: "Raven's Progressive Matrices",
          body: 'The canonical non-verbal, culture-reduced test of fluid reasoning. The Standard version is 60 items in five sets of increasing difficulty; the Advanced version discriminates at the high end. Every item is a 3×3 matrix with the last cell missing.',
        },
        {
          name: 'Cattell Culture Fair (CFIT)',
          body: 'Built explicitly to reduce cultural, linguistic and educational loading. Four timed subtests: series, classification, matrices and conditions. Reported on a scale with standard deviation 24, which is why a "Cattell 148" is roughly a "Wechsler 130".',
        },
        {
          name: 'Woodcock–Johnson IV',
          body: 'The most explicitly CHC-aligned battery: its subtests are deliberately mapped onto the broad and narrow abilities of the Cattell–Horn–Carroll model.',
        },
        {
          name: 'Short screeners',
          body: 'The Wonderlic (50 mixed items in 12 minutes) for occupational screening; CogAT and OLSAT as group school tests; the NNAT as a non-verbal school screener.',
        },
      ],

      verbalHeading: 'Why there are no vocabulary questions here',
      verbalP1:
        'Verbal analogies and vocabulary look easy to generate and are not. Their correctness depends on facts about a natural language that live outside the generator. A program can emit hot : cold :: up : ? only if a human has already told it that hot/cold and up/down are antonym pairs — which makes it a hand-authored content database with a lookup key, not a generator.',
      verbalP2:
        'Worse, the answer is not actually unique. For up : ? the intended answer is down, but above, upward and raised are all defensible depending on which relation you infer, and the program has no principled way to know which you meant. Every item here must have exactly one answer that can be proved correct, so verbal items are out.',
      verbalP3:
        "This is the same reason the deliberately culture-fair batteries — Raven's, Cattell, the NNAT — are purely non-verbal, and why practically every free online test is matrix-based.",

      guardsHeading: 'How an item is proved to be fair',
      guardsLede: 'Every generated item has to survive three checks before you see it.',
      guards: [
        {
          title: '1. A separate solver has to agree',
          body: 'An independent solver — deliberately not the code that produced the item — re-derives the rule from what is visible and lists every rule that fits. If two fitting rules predict different answers, the item is discarded. This is why you will never see 2, 4, 8, ? here: ×2 predicts 16 and a growing gap predicts 14, and both are defensible.',
        },
        {
          title: '2. The options must not give the answer away',
          body: 'A well-known research dataset of matrix problems turned out to be solvable without looking at the question at all: its wrong answers were made by tweaking one feature of the right one, so the right one was always the most "typical" option. Here the eight options form a balanced set in which every feature value appears in exactly half of them, so no such shortcut exists — and there is a test that tries the shortcut and confirms it scores at chance.',
        },
        {
          title: '3. Wrong answers have to be wrong for a reason',
          body: 'Distractors are built from specific mistakes — the rule applied down the columns instead of along the rows, the right rule counted one step too far, a cell simply copied. That way the explanation afterwards can name the mistake you probably made rather than only telling you that you made one.',
        },
      ],

      /**
       * The single most persuasive claim on the site, given room to be persuasive.
       *
       * "`2, 4, 8, ?` can never be emitted, because ×2 predicts 16 and a growing gap predicts
       * 14" is the argument that makes the whole generatability story concrete — and it was one
       * clause inside a paragraph. Stepped out, it demonstrates the check rather than asserting
       * it.
       */
      proof: {
        heading: 'The check, on one item',
        lede: 'Every generated item has to survive a solver that re-derives it from scratch. Here is what that rejects.',
        sequence: 'What comes next?',
        readingA: 'Read it as doubling',
        readingAWork: 'each term is twice the one before',
        readingAAnswer: '16',
        readingB: 'Read it as a growing gap',
        readingBWork: 'the gaps are 2, then 4, then 8',
        readingBAnswer: '14',
        verdict: 'Two rules fit what is visible and they disagree, so there is no defensible answer — and the item is discarded before anyone sees it.',
        verdictLabel: 'discarded',
      },

      difficultyHeading: 'Difficulty is controlled, not guessed',
      difficultyP1:
        'The number-series levels follow the cognitive operators from the published item-generation literature, in ascending order of load: reading a single sequence, then spotting two interleaved ones, then repeating blocks, then a gap that grows by a constant, then a multiplier that itself changes. Those five operators together explain roughly 77% of the variance in item difficulty — difficulty here is a property of the structure, not a label someone attached afterwards.',
      difficultyP2:
        'For matrices, difficulty comes from how many attributes carry a rule at once and how abstract those rules are. For mental rotation, from the angle and the number of cells — response time is known to rise linearly with rotation angle, which makes it a well-behaved dial.',

      automationHeading: 'Why the WAIS cannot be put online, and Raven-style items can',
      automationBody:
        'The dividing line is the response format, not the prestige of the test. Closed-response batteries — Raven\u2019s, the Cattell CFIT, the Wonderlic, the NNAT, ICAR — are fully machine-scorable, which is why they have web versions. The Wechsler family is not: Similarities, Vocabulary and Comprehension are open verbal answers scored against a rubric, and Block Design is physical manipulation, timed and observed by an examiner. That boundary is exactly the boundary of what this site covers, and it is the same one the vocabulary section above arrives at from the other direction — what a program can generate, and what a program can score, turn out to be the same set.',

      ceilingHeading: 'Where the scale runs out',
      ceilingP1:
        'Standard batteries lose resolution at the top. A WAIS or an Advanced Raven\u2019s has neither enough normative cases nor enough discriminating items much above 145–160: near the ceiling a single careless error moves the score by several points, so the measurement error is larger than the difference being measured.',
      ceilingP2:
        'A subculture of "high-range" tests exists to claim resolution up to 190. They buy it by going untimed and open-response — which removes guessing, but also means the test measures persistence, free time and puzzle obsession alongside reasoning. Their norms come from self-selected volunteers who chose to spend weeks on a puzzle set, which is close to the least representative sample imaginable, and rarity claims beyond about four standard deviations assume the normal curve holds in a tail where nobody has checked.',
      ceilingP3:
        'So the difficulty here stops at level 5, and that is a practice ladder rather than a measurement scale. If the hardest items feel too easy, that is a real limit of this design — and the usual cure for it costs more than it is worth.',

      notMeasuredHeading: 'What an IQ test does not measure at all',
      notMeasuredLede:
        'Even a perfectly administered battery measures the efficiency of certain reasoning and information-processing circuits. It is not a measurement of a mind. Outside its scope:',
      notMeasured: [
        {
          title: 'Divergent creativity',
          body: 'Generating original ideas outside a scored frame. Single-answer items are the opposite construct by design — this whole site is built on there being exactly one defensible answer.',
        },
        {
          title: 'Emotional and social intelligence',
          body: 'Empathy, emotion regulation, reading a room, negotiating, tolerating stress.',
        },
        {
          title: 'Practical and adaptive competence',
          body: 'Resourcefulness, situational judgement, everyday problem solving. Adaptive-behaviour scales exist as separate instruments precisely because a Full Scale IQ does not cover this.',
        },
        {
          title: 'Personality and conation',
          body: 'Conscientiousness, curiosity, persistence, motivation. These predict real-world outcomes at least as strongly as g in many domains.',
        },
      ],
      notMeasuredClose:
        'That applies recursively to this site. High accuracy on these thirteen formats is evidence about these thirteen formats, and about nothing else.',

      difficultyP3:
        'What that does not amount to is calibration. The bands are *designed* from published cognitive operators — a defensible ordering — but no item here carries a difficulty parameter fitted to real response data, which is what item-response theory means by difficulty. So the adaptive ladder is a staircase that keeps you near your own success rate, not an estimate of your ability.',
      limitsHeading: 'The limitations, stated plainly',
      limits: [
        {
          title: 'No norms means no score.',
          body: 'Without a representative sample to compare you against, a percentile or an "IQ 132" would be invented. This site reports accuracy, speed and change over time, which are things it can actually measure.',
        },
        {
          title: 'Practice effects are large, and they are the point.',
          body: 'Taking a test a second time typically raises the score by 5–15 points, and the effect is largest for novel formats like matrix reasoning — exactly what a training site drills. Clinical practice recommends at least twelve months between administrations of the same instrument for this reason. Training makes you better at the task. There is no good evidence it raises g.',
        },
        {
          title: 'Norms drift.',
          body: 'The Flynn effect — average scores rising by roughly 3 points per decade in developed countries — is why batteries are renormed every 15–20 years. Any fixed conversion table goes stale.',
        },
        {
          title: 'Unproctored and self-selected.',
          body: 'You are testing yourself, at a time you chose, in an environment nobody controlled, with your phone within reach. That is the standard critique of online testing and it applies here in full.',
        },
        {
          title: 'Nothing here is copied from a published test.',
          body: "Real Wechsler, Raven's and Cattell items are copyrighted and often trade-secret protected. Every item on this site is generated from scratch. The formats are described in the open literature and are not themselves protectable. Test names appear here descriptively, to say which published instrument a format resembles — never as a product claim. This site is not affiliated with, endorsed by, or a version of any of them.",
        },
      ],

      dataHeading: 'Your data',
      dataBodyBefore:
        "Everything is kept in this browser's localStorage and never leaves your device — the site is a set of static files with no backend to send anything to. Sessions are stored as seeds, not as items, which is why the whole history takes a few kilobytes. You can export it, import it elsewhere, or delete it from the ",
      dataLink: 'progress page',
      dataBodyAfter: '.',

      sourcesHeading: 'Sources',
      sources: [
        'Zhang et al., RAVEN: A Dataset for Relational and Analogical Visual rEasoNing, CVPR 2019 — the attribute/rule scheme used for the matrices.',
        "Hu et al., Stratified Rule-Aware Network (I-RAVEN) — the context-blind flaw in RAVEN's distractors and the fix.",
        "Wang & Su, Automatic Generation of Raven's Progressive Matrices, IJCAI 2015 — well-formedness criteria and the distractor error-type taxonomy.",
        'Hornke & Habon (1986) — the original procedural rule set for Raven-like matrices.',
        'Arendasy & Sommer; Zhang et al. — the ANSIG cognitive operators for number-series difficulty.',
        'Shepard & Metzler (1971); Vandenberg & Kuse (1978) — mental rotation.',
        'Schneider & McGrew (2018) — the Cattell–Horn–Carroll framework.',
        'Flynn; Kanaya, Scullin & Ceci — the Flynn effect and renorming.',
        'Condon & Revelle, the International Cognitive Ability Resource (ICAR) — the one open, IRT-calibrated, properly licensed item bank. Deliberately not used here: a fixed bank of a few dozen items is exhausted in a single session, which is the problem generation exists to solve.',
      ],
      sourcesNote:
        'The full research notes, the generatability analysis, and the library evaluation live in the docs/ directory of the repository.',
    },

    terms: {
      title: 'Terms of use',
      description:
        'What this site is, what it is not, and the terms under which it is provided. It produces no IQ score and is not an assessment or diagnostic instrument.',
      lede: 'This site offers practice on reasoning-question formats. It produces no IQ score, is not a psychometric test, and is in no way a substitute for assessment by a psychologist.',
      updated: 'Last updated: August 2026',
      sections: [
        {
          heading: 'Purpose of this site',
          body: [
            'This site provides, free of charge, algorithmically generated exercises based on the question formats used in aptitude and intelligence tests. Its purpose is educational and recreational: to understand how such items are built, and to practise them. It runs entirely in the browser, with no account and no server.',
          ],
        },
        {
          heading: 'This is not an assessment instrument',
          body: [
            'No IQ score, percentile, rank or level is produced, and none can be: an IQ score is a comparison against a representative standardisation sample, taken under standardised conditions, and this site has neither. The figures shown — accuracy, response time, progress — describe your performance on this site and nothing else.',
            'In particular they cannot detect, confirm or rule out giftedness, a learning disorder, a cognitive impairment or any other condition. Only a qualified psychologist or neuropsychologist can carry out such an assessment, using a standardised battery administered face to face. This site must not be used as the basis for any decision about education, recruitment, schooling or health.',
          ],
        },
        {
          heading: 'No warranty',
          body: [
            'The content is provided "as is", with no warranty as to accuracy, completeness, availability or fitness for any particular purpose. Items are generated and verified automatically; despite the checks in place, an error in a question, an explanation or an expected answer remains possible.',
            'No result, no improvement and no success on any later test is guaranteed — practice improves performance on the exercise practised, which does not necessarily transfer elsewhere.',
          ],
        },
        {
          heading: 'Limitation of liability',
          body: [
            'The author cannot be held liable for any direct or indirect damage arising from use of the site, from the interpretation of its results, or from any decision taken on the basis of them. Use of the site is entirely at your own risk.',
          ],
        },
        {
          heading: 'Intellectual property and trade marks',
          body: [
            'The site\u2019s code is published under the MIT licence; the explanatory texts may be read freely for personal use, with a short quotation and a link if reused. No item from any published test is reproduced: every question is generated by an algorithm from logical principles described in the scientific literature, and those principles are not protectable.',
            'The test names mentioned (WAIS, WISC, Raven\u2019s Progressive Matrices, Cattell, Wonderlic, NNAT and others) are trade marks belonging to their respective owners, and are mentioned descriptively only, to situate a question format. This site is neither affiliated with nor endorsed by those publishers, and offers no online version of their tests.',
          ],
        },
        {
          heading: 'External links and tools',
          body: [
            'Bibliographic references and external links are provided for documentation purposes; the author has no control over their content and accepts no responsibility for it.',
          ],
        },
        {
          heading: 'Personal data',
          body: [
            'The site is a set of static files: there is no application server, no account, no analytics cookie and no tracker. Your answers, your sessions and your preferences are kept only in your browser\u2019s local storage (localStorage), on your device, and are sent nowhere. You can export, re-import or erase them at any time from the Progress page.',
            'The host (GitHub Pages) may, for its part, log technical connection data under its own terms.',
          ],
        },
        {
          heading: 'Changes, availability and governing law',
          body: [
            'The content of the site and these terms may change without notice; the version online is the one that applies. Availability is not guaranteed, as hosting is provided by GitHub Pages.',
            'These terms are governed by French law; failing an amicable settlement, the French courts have jurisdiction. The French version prevails in case of divergence.',
          ],
        },
      ],
      publisherLabel: 'Publisher / contact',
      publisher: 'TODO — publisher name not yet supplied (see docs/PLAN-2026-08.md §1.2)',
      contactLabel: 'Contact',
      contact: 'https://github.com/aureliendrouet/flex-your-neurons/issues',
      hostLabel: 'Host',
      host: 'GitHub, Inc., 88 Colin P. Kelly Jr Street, San Francisco, CA 94107, USA',
    },

    redirect: {
      title: 'Choosing your language…',
      body: 'If you are not redirected automatically, choose a language:',
    },
  },
};

export default en;
